#pragma once
#include <argument_define.h>


enum NODE_EVENT_TYPE
{
	NODE_EVENT_START = -1,
	NODE_EVENT_INIT,
	NODE_EVENT_RENDER,
	NODE_EVENT_CLEAN,
	NODE_EVENT_KEY_INPUT,
	NODE_EVENT_END,
};

enum BUTTON_EVENT_TYPE
{
	BUTTON_EVENT_START = -1,
	BUTTON_MOUSE_OUT,
	BUTTON_MOUSE_OVER_MOTION,
	BUTTON_MOUSE_DOWN,
	BUTTON_MOUSE_UP,
	BUTTON_EVENT_END,
};

enum RENDER_EVENT_TYPE
{
	RENDER_EVENT_INIT = 0,
	RENDER_EVENT_DRAW,
	RENDER_EVENT_CLEAN,
	RENDER_EVENT_KEY_INPUT,
	RENDER_EVENT_LOOP,
	RENDER_EVENT_END,
};